# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7df87e03dad1c7e6d91beb64f4ae290da7a4521279461a9fe16e52f6ba8936e42f1241544f949d1a62f9fc91aaece41cbcf4b12bc598730f50b840a488bb006f

test:
  secret_key_base: 4571069263b3e8650db18318e4ad71f44870a800618583f52d67d322912491644870e92b56e9c92bc6989722d67636fa603702e0cdea33ff953496e4ebb6278c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
